# Deployment secrets - DO NOT COMMIT TO GIT
# Copy this file and fill in your actual values

[deployment.anvil]
rpc-url = "http://127.0.0.1:8545"
private-key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
etherscan-api-key = ""

[deployment.ethereum-mainnet]
rpc-url = ""  # e.g. "https://mainnet.infura.io/v3/YOUR_API_KEY"
private-key = ""  # Your private key (use Fireblocks in production)
etherscan-api-key = ""  # Your Etherscan API key
fireblocks-api-key = ""  # Your Fireblocks API key

[deployment.ethereum-sepolia]
rpc-url = ""  # e.g. "https://sepolia.infura.io/v3/YOUR_API_KEY"  
private-key = ""  # Your private key (use Fireblocks in production)
etherscan-api-key = ""  # Your Etherscan API key
fireblocks-api-key = ""  # Your Fireblocks API key