[deployment.anvil]
name = "Anvil"
id = 31337
admin = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
zkc = "0x0fd05be44c0ecfa2d6123a2f46c58e7489b7d189"
zkc-impl = "0x2413aa120ec4bc00b02d6ba0d8bcde7638c7e49f"
zkc-impl-prev = ""
vezkc = "0x0314000e284c880923dfdf684fc8a1fe4b51d477"
vezkc-impl = "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6"
vezkc-impl-prev = "0x4204f4bb4f31f0d8b838e7082fb9c77e2f5d6f08"
staking-rewards = "0x8a3ee54375fa125116a2c767e2a75e1616b20437"
staking-rewards-impl = "0xebba801757838bb5bf503a74a01d0146f554b20b"
staking-rewards-impl-prev = ""
povw-minter = "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
staking-minter = ""
deployment-commit = "46e6dba"

[deployment.ethereum-mainnet]
name = "Ethereum Mainnet"
id = 1
admin = ""
zkc = ""
zkc-impl = ""
zkc-impl-prev = ""
vezkc = ""
vezkc-impl = ""
vezkc-impl-prev = ""
staking-rewards = ""
staking-rewards-impl = ""
staking-rewards-impl-prev = ""
povw-minter = ""
staking-minter = ""
deployment-commit = ""

[deployment.ethereum-sepolia]
name = "Ethereum Sepolia"
id = 11155111
admin = ""
zkc = ""
zkc-impl = ""
zkc-impl-prev = ""
vezkc = ""
vezkc-impl = ""
vezkc-impl-prev = ""
staking-rewards = ""
staking-rewards-impl = ""
staking-rewards-impl-prev = ""
povw-minter = ""
staking-minter = ""
deployment-commit = ""