[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
via_ir = true
optimizer = true
optimizer_runs = 200
build_info = true
build_info_path = "out/build-info"
extra_output = ["storageLayout"]
ffi = true
fs_permissions = [
  { access = "read", path = "out" },
  { access = "read-write", path = "deployment.toml" },
  { access = "read", path = "build-info-reference" }
]
no_match_path = "**/deployment/**"

# Profile for building reference contracts
[profile.reference]
out = "out-reference"
cache_path = "cache-reference"
build_info = true
build_info_path = "out-reference/build-info"
extra_output = ["storageLayout"]

# Profile for deployment testing
[profile.deployment-test]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [
  { access = "read", path = "out" },
  { access = "read", path = "deployment.toml" },
  { access = "read", path = "deployment_secrets.toml" }
]

# Invariant testing configuration
[invariant]
runs = 50                    # Faster execution while maintaining good coverage
depth = 50                  # Sufficient depth for complex state evolution
fail_on_revert = false      # Don't fail on individual reverts
call_override = false       # Use default call behavior
dictionary_weight = 80      # Weight for using dictionary values

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
